### ISSUE TITLE
🇮🇹 Bug greenpass tampone

### ISSUE THREAD

**Issue by quellopiubello** [masterix21/green-pass#4]
Buongiorno,

scansionando un greenpass ottenuto da tampone mi restituisce il seguente errore:

```
[Thu Dec 02 10:14:12.960644 2021] [php:error] [pid 21] [client 10.20.3.1:40038] PHP Fatal error:  Uncaught InvalidArgumentException: Out of range. Expected: 1, read: 0. in /var/www/html/vendor/spomky-labs/cbor-php/src/StringStream.php:53\nStack trace:\n#0 /var/www/html/vendor/spomky-labs/cbor-php/src/Decoder.php(48): CBOR\\StringStream->read()\n#1 /var/www/html/vendor/spomky-labs/cbor-php/src/Decoder.php(43): CBOR\\Decoder->process()\n#2 /var/www/html/vendor/masterix21/green-pass/src/Services/Decoder.php(58): CBOR\\Decoder->decode()\n#3 /var/www/html/vendor/masterix21/green-pass/src/Services/Decoder.php(74): Masterix21\\GreenPass\\Services\\Decoder::cose()\n#4 /var/www/html/test.php(14): Masterix21\\GreenPass\\Services\\Decoder::qrcode()\n#5 {main}\n  thrown in /var/www/html/vendor/spomky-labs/cbor-php/src/StringStream.php on line 53
```

Scansionando QR da vaccino sembra tutto ok.
E' mai successo questo problema?

Grazie e saluti.

**Comment by masterix21** [comment]
Se utilizzavi un lettore di qrcode, probabilmente aggiungeva i caratteri newline (`\n` e/o `\r`).

Posso chiudere la issue?

**Comment by quellopiubello** [comment]
Si grazie e scusami il disturbo.

Il giorno gio 2 dic 2021 alle ore 14:31 Luca Longo ***@***.***>
ha scritto:

**Comment by masterix21** [comment]
Grazie a te.
